In [ ]:
def getDCG(scores):
    return np.sum(
        np.divide(np.power(2, scores) - 1, np.log(np.arange(scores.shape[0], dtype=np.float32) + 2)),
        dtype=np.float32)

def getNDCG(rank_list, pos_items):
    relevance = np.ones_like(pos_items)
    it2rel = {it: r for it, r in zip(pos_items, relevance)}
    rank_scores = np.asarray([it2rel.get(it, 0.0) for it in rank_list], dtype=np.float32)

    idcg = getDCG(np.sort(relevance)[::-1])

    dcg = getDCG(rank_scores)

    if dcg == 0.0:
        return 0.0

    ndcg = dcg / idcg
    return ndcg

def recall_N(y_true, y_pred, N=50):
    return len(set(y_pred[:N]) & set(y_true)) * 1.0 / len(y_true)

In [1]:
import random

In [4]:
nested_lists = [[1, 2], [[3, 4], [5, 6], [[7, 8], [9, 10], [[11, [12, 13]]]]]]
flatten = lambda x: [y for l in x for y in flatten(l)] 
if type(x) is list else [x]
flatten(nested_lists)

In [5]:
class Model1:
    def __init__(self, hidden_size=100, num_layers=3, learning_rate=3e-4):
        print(locals())
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.learning_rate = learning_rate

model1 = Model1()

In [6]:
class Model2:
    def __init__(self, hidden_size=100, num_layers=3, learning_rate=3e-4):
        params = locals()
        del params['self']
        self.__dict__ = params

model2 = Model2()
model2.__dict__

In [7]:
class Model3:
    def __init__(self, **kwargs):
        self.__dict__ = kwargs

model3 = Model3(hidden_size=100, num_layers=3, learning_rate=3e-4)
model3.__dict__

dict_items([('a', 2), ('b', 1), ('c', 1), ('d', 3), ('e', 2), ('f', 2)])

In [8]:
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6, 0])
index_val = np.argpartition(x, 3)

array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])
np.allclose(array1,array2,0.1)

x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])
np.clip(x,2,5)

#  Divide by 2 and check if remainder is 1
array = np.random.randint(20, size=12)
cond = np.mod(array, 2)==1
np.extract(cond, array)
np.extract(((array < 3) | (array > 15)), array)

y = np.array([1,5,6,8,1,7,3,6,9])
np.where(y>5, "Hit", "Miss")

a = np.array([1,5,6,8,1,7,3,6,9])
np.percentile(a, 50, axis =0)

In [9]:
count.items()

dict_items([('a', 3), ('b', 2), ('c', 2), ('d', 3), ('e', 2), ('f', 2)])

In [13]:
#count.update({'a':3})
count.subtract('abc')
count.items()

dict_items([('a', 5), ('b', 1), ('c', 1), ('d', 3), ('e', 2), ('f', 2)])

In [14]:
import numpy as np

In [19]:
a = np.random.rand(5,4)

In [23]:
np.where(a>0.5,-a, a)

array([[-0.67257599, -0.98233062,  0.40572481,  0.39151566],
       [-0.66463821, -0.76714931, -0.93402735, -0.51984491],
       [ 0.47698048, -0.67323628,  0.35411329, -0.94468792],
       [-0.74695841,  0.44868593, -0.94323902, -0.75891856],
       [-0.69531875,  0.44533793, -0.82410758,  0.40319748]])

In [24]:
np.random.permutation(5)

array([0, 3, 2, 4, 1])

In [28]:
np.argmin(a,axis=1)

array([3, 3, 2, 1, 3], dtype=int64)

In [29]:
np.dot(a,np.array([1,1,1,1]))

array([2.45214708, 2.88565979, 2.44901798, 2.89780191, 2.36796174])

In [ ]:
fig = plt.figure() #调用figure创建一个绘图对象
ax = fig.add_subplot(111)
cax = ax.matshow(correlations, vmin=-1, vmax=1)  #绘制热力图，从-1到1
fig.colorbar(cax)  #将matshow生成热力图设置为颜色渐变条
ticks = numpy.arange(0,9,1) #生成0-9，步长为1
ax.set_xticks(ticks)  #生成刻度
ax.set_yticks(ticks)
ax.set_xticklabels(names) #生成x轴标签
ax.set_yticklabels(names)
plt.show()