In [1]:
import numpy as np

In [ ]:
apply_along_axis, argmax, argmin, argsort, 
average, bincount, ceil, clip, conj, corrcoef, cov, 
cross, diff, dot, floor, inner, inv, 
lexsort, maximum, mean, median, minimum, 
nonzero, outer, prod, re, trace, 
transpose, var, vdot, vectorize, where

Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
Questions
all, any, nonzero, where
Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
Basic Statistics
cov, mean, std, var
Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

In [ ]:
np.tile(x[None,:],(10,1)),np.tile(y[:,None],(1,10)) = np.meshgrid(x,y)
# See if both the train and test label distribution are similarly distributed
train_unique_label, train_counts_label = np.unique(original_ytrain, 
                                                   return_counts=True)
np.apply_along_axis(lambda x: np.argmax(np.bincount(x)),
                axis=1, arr=z) 

#Argpartition：在数组中找到最大的 N 个元素。
import numpy as np
array = np.array([10, 7, 4, 3, 2, 2, 5, 9, 0, 4, 6, 0])
index = np.argpartition(array, 5)[-5:]
index

np.sort(array[index])

# Extract：从数组中提取符合条件的元素
arr = np.arange(10)
condition = np.mod(arr, 3)==0
np.extract(condition, arr)
array([0, 3, 6, 9])
np.extract(((arr > 2) & (arr < 8)), arr)

# setdiff1d：如何找到仅在 A 数组中有而 B 数组没有的元素
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([3,4,7,6,7,8,11,12,14])
c = np.setdiff1d(a,b)
carray([1, 2, 5, 9])

In [ ]:
x = np.arange(10)
condlist = [x<3, x>5]
choicelist = [x, x**2]
np.select(condlist, choicelist)

import numpy as np
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=np.where(cond,xarr,yarr);result

arr=np.random.randn(4,6)
np.where(arr>0,np.array([1,2,3,4,5,6]),arr)#自动进行broadcast
#np.where(cond1&cond2,0,np.where(cond1,1,np.wher(cond2,2,3)))

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [2]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
print(nz)
C = np.array([[0,5,9],
              [4,0,10]])
print(np.nonzero(C))
print(np.clip(C,5,9))

(array([0, 1, 4], dtype=int64),)
(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))
[[5 5 9]
 [5 5 9]]




#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 6.  6.  8. -9.  7. -9.  9.  8.  2.  4.]


In [3]:
np.copysign(-3,3)

3.0

#### 30. How to find common values between two arrays? (★☆☆)

In [4]:
# 寻找共同元素
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
np.intersect1d(Z1, Z2)

array([0, 5, 7])

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [7]:
a = map(lambda x:x**2, range(10))
Z = np.fromiter(a, dtype=float, count=-1)
print(Z)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
A = np.random.randint(0,2,6)
B = np.random.randint(0,2,5)
def array_equal(A,B):
    if A.shape != B.shape:
        return False
    return (A==B).all()
array_equal(A,B)

((6,), tuple)

In [ ]:
#Make an array immutable
Z = np.zeros(10)
Z.flags.writeable = False

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [32]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z[0,0])

(0., 0.)


$C_{i,j} = X_i-Y_j$

In [28]:
C = 1.0 / np.subtract.outer(X, Y)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [35]:
Z = np.zeros(2, [('position', [ ('x', float, (1,2)),
                                  ('y', float, (1,))]),
                   ('color',    [ ('r', float, (1,)),
                                  ('g', float, (1,)),
                                  ('b', float, (1,))])])
Z

array([(([[0., 0.]], [0.]), ([0.], [0.], [0.])),
       (([[0., 0.]], [0.]), ([0.], [0.], [0.]))],
      dtype=[('position', [('x', '<f8', (1, 2)), ('y', '<f8', (1,))]), ('color', [('r', '<f8', (1,)), ('g', '<f8', (1,)), ('b', '<f8', (1,))])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

In [37]:
import scipy
import scipy.spatial
#find point by point distances
Z = np.random.random((10,3))
D = scipy.spatial.distance.cdist(Z,Z)

(10, 10)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
# numpy中的enumerate
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [38]:
n,p = 5,3
Z = np.zeros((n,n))
'''Replaces specified elements of an array with given values.
The indexing works on the flattened target array.'''
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

In [46]:
#How to sort an array by the nth column? 
Z = np.random.randint(0,10,(3,3))
print(Z[Z[:,1].argsort()])

[[8 4 4]
 [8 6 8]
 [1 9 6]]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.3388283390062511


In [81]:
#Consider a given vector, add 1 to each element indexed by another vector
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)
# accumulate elements of a vector to an array based on an index list
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

# how to get sum over the last two axis at once
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

[1. 2. 3. 5. 2. 4. 4. 1. 6. 2.]


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.43740433, 1.30533245, 1.32379824, 2.46896817, 0.67545867])

#### 73. Consider a set of 10 triplets describing 10 triangles  (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  9) ( 0, 11) ( 0, 59) ( 0, 91) ( 1,  8) ( 1, 47) ( 1, 69) ( 1, 82)
 ( 3, 40) ( 3, 97) ( 5,  9) ( 5, 73) ( 8, 47) ( 9, 11) ( 9, 73) (13, 53)
 (13, 56) (13, 58) (13, 99) (16, 62) (16, 82) (28, 84) (28, 87) (40, 97)
 (53, 99) (56, 58) (59, 91) (62, 82) (69, 82) (84, 87)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

In [77]:
def rolling(a,window):
    index = [a[slice(i,-window+i)] for i in range(window)]
    z = np.vstack(index).T
    return z 
rolling(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [78]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.70672797 7.69612039 2.25784974 4.60168732 1.86333395 0.34324433
 0.81905363 1.00428102 4.4882624  5.52240104]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [79]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.51631169  6.42167595  4.90471349  8.92152608  0.64430522 13.1477316
   4.82647115 14.35803776  2.83869333  5.78536237]
 [11.72333193  2.28525701  4.48035411 11.29872486 14.10963053  4.49070061
   6.06173032  5.24835195  3.32272461 11.12005469]
 [ 7.68423685  3.99209265 12.25140797  4.74391157  4.67770228  5.40024792
   5.31689533  8.63226702  7.63625936  2.4274878 ]
 [ 4.72217595  8.25441437  1.85343282  1.41186727  8.5013649   8.04308066
   3.56471625  7.66668404  3.79347479  1.17033352]
 [ 4.61970509  1.82880232  0.88155845  3.87855982  7.49446718  1.13451433
   3.69653461  1.60058913  2.96229578  5.89123061]
 [ 1.71064014  2.13236159  2.87428566  0.42743983  4.85508373  3.972235
   2.17049563  4.87642258  2.29807957  3.20458539]
 [ 1.10951331  3.52006522  2.73748642  1.39980831  4.49782435  6.00139265
   0.34929072  6.82585741  0.76526847  1.17624526]
 [ 0.56577927  0.63802769  4.85499764  1.49919907  3.40600949  1.94224115
   4.85430884  3.39018238  5.08047535  5.36034047]
 [ 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [80]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 3 2 8 2 6 7 3 0 8]
 [8 9 7 6 1 5 2 4 6 1]
 [1 6 2 0 2 4 0 3 4 8]
 [8 0 8 0 8 4 6 3 3 1]
 [6 0 4 9 5 3 0 5 3 0]
 [6 7 5 4 3 7 9 0 9 6]
 [7 1 8 4 1 9 0 8 8 0]
 [7 8 4 9 4 0 0 6 5 7]
 [9 3 5 8 7 2 6 5 5 7]
 [7 9 6 7 8 7 7 8 8 7]]
[[0 0 0 0 0]
 [0 4 3 2 8]
 [0 8 9 7 6]
 [0 1 6 2 0]
 [0 8 0 8 0]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [81]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [82]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [83]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 2]
   [4 3 4]
   [4 2 4]]

  [[0 2 0]
   [3 4 0]
   [2 4 3]]

  [[2 0 1]
   [4 0 0]
   [4 3 3]]

  [[0 1 1]
   [0 0 0]
   [3 3 2]]

  [[1 1 0]
   [0 0 1]
   [3 2 4]]

  [[1 0 4]
   [0 1 3]
   [2 4 1]]

  [[0 4 2]
   [1 3 4]
   [4 1 1]]

  [[4 2 2]
   [3 4 4]
   [1 1 3]]]


 [[[4 3 4]
   [4 2 4]
   [3 0 3]]

  [[3 4 0]
   [2 4 3]
   [0 3 0]]

  [[4 0 0]
   [4 3 3]
   [3 0 3]]

  [[0 0 0]
   [3 3 2]
   [0 3 4]]

  [[0 0 1]
   [3 2 4]
   [3 4 2]]

  [[0 1 3]
   [2 4 1]
   [4 2 2]]

  [[1 3 4]
   [4 1 1]
   [2 2 0]]

  [[3 4 4]
   [1 1 3]
   [2 0 2]]]


 [[[4 2 4]
   [3 0 3]
   [2 4 3]]

  [[2 4 3]
   [0 3 0]
   [4 3 0]]

  [[4 3 3]
   [3 0 3]
   [3 0 3]]

  [[3 3 2]
   [0 3 4]
   [0 3 3]]

  [[3 2 4]
   [3 4 2]
   [3 3 1]]

  [[2 4 1]
   [4 2 2]
   [3 1 2]]

  [[4 1 1]
   [2 2 0]
   [1 2 1]]

  [[1 1 3]
   [2 0 2]
   [2 1 3]]]


 [[[3 0 3]
   [2 4 3]
   [3 0 4]]

  [[0 3 0]
   [4 3 0]
   [0 4 1]]

  [[3 0 3]
   [3 0 3]
   [4 1 1]]

  [[0 3 4]
   [0 3 3]
   [1 1 4]]

  [[3 4 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [85]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 16  6  5  6]
 [16  5 13 16 12]
 [ 6 13  4 42  2]
 [ 5 16 42  2 13]
 [ 6 12  2 13  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [86]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [87]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 89. How to get the n largest values of an array (★★★)

In [89]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [90]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [91]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [93]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [94]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 1]
 [3 4 1]
 [0 2 4]
 [4 1 4]
 [3 4 4]
 [3 2 1]
 [3 0 3]
 [2 1 0]
 [3 0 3]
 [0 1 2]]
[[3 4 1]
 [0 2 4]
 [4 1 4]
 [3 4 4]
 [3 2 1]
 [3 0 3]
 [2 1 0]
 [3 0 3]
 [0 1 2]]
[[3 4 1]
 [0 2 4]
 [4 1 4]
 [3 4 4]
 [3 2 1]
 [3 0 3]
 [2 1 0]
 [3 0 3]
 [0 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [95]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [96]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 1 0]]
[[0 0 1]
 [0 1 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [97]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.06728041, 0.05397444, 0.0764441 , 0.22359054, 0.0836961 ,
        0.23600838, 0.01241854, 0.22915715, 0.07803804, 0.18796029],
       [0.17717534, 0.14213557, 0.20130688, 0.58880039, 0.22040419,
        0.62150136, 0.03270283, 0.60345942, 0.20550435, 0.49497216],
       [0.27189413, 0.21812194, 0.30892651, 0.90357594, 0.33823335,
        0.95375901, 0.05018592, 0.92607176, 0.31536797, 0.75958668],
       [0.06789412, 0.05446677, 0.07714139, 0.22563006, 0.08445954,
        0.23816117, 0.01253182, 0.23124745, 0.07874988, 0.1896748 ],
       [0.11831111, 0.09491285, 0.13442526, 0.39317904, 0.14717774,
        0.41501553, 0.02183773, 0.40296779, 0.13722817, 0.33052403],
       [0.23778707, 0.19076019, 0.27017402, 0.79022918, 0.29580454,
        0.83411717, 0.04389047, 0.80990307, 0.27580745, 0.66430229],
       [0.03397511, 0.02725589, 0.03860257, 0.11290827, 0.04226467,
        0.119179  , 0.00627109, 0.11571928, 0.03940748, 0.09491578],
       [0.08646755, 0.06936696, 0.0982445

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [98]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [100]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30976616  0.02882422]
