In [1]:
import pandas as pd
import numpy as np
import os
os.chdir('D:/DataSet/翼支付')

- sex 需要填补缺失值
- age 暂不处理
- provider one-hot编码
- level 暂不处理
- verified 不处理
- using_time 不处理
- regist_type one-hot
- card_a/b/c/d_cnt 暂不处理
- op1/2_cnt 暂不处理
- service1/2_cnt 暂不处理
- service2_amt 暂不处理
- agreement_total 暂不处理
- agreement1/2/3/4 不处理
- acc_count 暂不处理
- login_cnt_period1/2 暂不处理
- ip_cnt 暂不处理
- login_cnt_avg 暂不处理
- login_days_cnt 暂不处理
- province 编码
- city 暂时删除
- balance/1/2/balance/1/2_avg 暂不处理
- service3  是否服务3用户
- service3_level  服务3等级, 没有开通服务3的没有service3_level数据
- product1/2/3/4/5/6_amount 不处理
- product7_cnt 不处理
- product7_fail_cnt 不处理

In [22]:
data['level'].unique()

array([2., 1., 0.])

In [27]:
data.groupby(data['service3_level'].isnull())['label'].mean()

service3_level
False    0.040173
True     0.265046
Name: label, dtype: float64

In [28]:
data['service3_level'].isnull().value_counts()

True     43849
False     3933
Name: service3_level, dtype: int64

In [29]:
testdata['service3_level'].isnull().value_counts()

True     23080
False     1235
Name: service3_level, dtype: int64

In [32]:
data['service3'].value_counts()

0.0    43849
1.0     3933
Name: service3, dtype: int64

In [33]:
data['service3_level'].unique()

array([nan, 'category 0', 'category 3', 'category 1', 'category 2'],
      dtype=object)

In [2]:
df = pd.read_csv('./train/train_base.csv')

In [6]:
label = pd.read_csv('./train/train_label.csv')

In [7]:
data = pd.merge(df, label, left_on='user', right_on='user')

In [8]:
label['label'].value_counts()

0    36002
1    11780
Name: label, dtype: int64

In [9]:
cate = data.select_dtypes(include='object')

In [14]:
NO_USE_COLUMNS = ['user', 'province', 'city', 'service3_level']
columns = cate.columns.difference(set(NO_USE_COLUMNS))
for column in columns:
    data[column] = cate[column].str.split(' ').str[1]
    data[column] = data[column].astype(float)
    
testdata = pd.read_csv('./test/test_a_base.csv')
for column in columns:
    testdata[column] = testdata[column].str.split(' ').str[1]
    testdata[column] = testdata[column].astype(float)

In [16]:
num = data.select_dtypes(exclude='object')

In [18]:
num.nunique()

sex                     2
age                    48
provider                3
level                   3
verified                2
using_time             54
regist_type             8
card_a_cnt             18
card_b_cnt             11
card_c_cnt             15
agreement1              2
op1_cnt                31
op2_cnt                17
card_d_cnt              4
agreement_total        21
service1_cnt            7
service1_amt           58
service2_cnt            6
agreement2              2
agreement3              2
agreement4              2
acc_count              66
login_cnt_period1    2692
login_cnt_period2    1566
ip_cnt                193
login_cnt_avg          76
login_days_cnt         91
balance                20
balance_avg            21
balance1               21
balance1_avg           21
balance2               20
balance2_avg            5
service3                2
product1_amount         7
product2_amount        21
product3_amount         3
product4_amount         2
product5_amo

In [21]:
data['sex'].unique()

array([ 1.,  0., nan])

In [34]:
mask = data['service3_level'].isnull()
data1 = data.loc[~mask,:]
data2 = data.loc[mask,:]

In [36]:
data1['label'].value_counts()

0    3775
1     158
Name: label, dtype: int64

In [40]:
data1.groupby('service3_level')['label'].mean()

service3_level
category 0    0.078209
category 1    0.012486
category 2    0.002381
category 3    0.000000
Name: label, dtype: float64

In [41]:
data1['service3_level'].value_counts()

category 0    1854
category 1     881
category 2     840
category 3     358
Name: service3_level, dtype: int64

In [84]:
data2['service3'].value_counts()

0.0    43849
Name: service3, dtype: int64

In [85]:
data2.groupby('province')['label'].mean()

province
05b65ab01d19bc64    0.272059
07195ac14eb7c124    0.222222
1c78bbcfd5d34a7a    0.265161
21c43413032d5522    0.238254
322eedef621f1b51    0.294979
4537ea65a48e5fc2    0.231707
4939d22f7c80736c    0.256569
494915bbe9c3782f    0.219067
58ce8e1e1ae2da04    0.287190
5f5c1abc4530f9d9    0.191268
648024953e363510    0.242773
6b3c8e3d6666ebef    0.254603
6c35e7246f6d4e1c    0.298093
6d3d7a5255b706f1    0.293669
6dd7071b6edc22d2    0.280848
6fe245ff773f634d    0.235621
71c3649e6dfc18fe    0.322455
74c577b6f0e1332c    0.227451
7fb40ca1dc4972a0    0.230225
89ec545a3e1e73a8    0.204082
8f730d6bf0fd60a3    0.327189
90c35f1c2384a466    0.396748
9441fd3d54d5fb9c    0.244074
993a795b56eef075    0.268188
a67a84d872135c3c    0.242481
c333319f1964450d    0.213220
c3e48f852a0da7b6    0.364700
e0355ab057d491d9    0.197452
e6c2bd43d3384f1d    0.302128
f44d49ef80e942ff    0.242271
ff6271b886557ee9    0.363636
Name: label, dtype: float64

In [91]:
index = data2['city'].value_counts()[:50].index

In [92]:
city = data2.loc[data2['city'].isin(index),:]

In [113]:
data2.groupby(['agreement2','agreement3','agreement4'])['label'].mean()

agreement2  agreement3  agreement4
0.0         0.0         0.0           0.335204
                        1.0           0.316652
            1.0         0.0           0.208180
                        1.0           0.178846
1.0         0.0         0.0           0.275070
                        1.0           0.199284
            1.0         0.0           0.184428
                        1.0           0.115037
Name: label, dtype: float64

In [116]:
(data2['agreement_total']-24700).value_counts().sort_index()

6       185
12      955
19     1046
25     3462
31     6058
37     6939
43     6932
49     6000
55     4604
61     3240
67     2100
74     1177
80      632
85      307
91      137
98       43
104      25
110       5
116       1
129       1
Name: agreement_total, dtype: int64

In [151]:
data2['verified'].value_counts()


0.0    42286
1.0     1563
Name: verified, dtype: int64

In [ ]:
# 剔除product4_amount, product5_amount
# producct1/2/3/5_amount分为level1和其他

In [149]:
data1['product5_amount'].value_counts()

0.0    3768
1.0     165
Name: product5_amount, dtype: int64

In [ ]:
# data1剔除verified